# Generated by Django 2.0.6 on 2018-10-25 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentresult',
            name='bull',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='currentresult',
            name='cow',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='currentresult',
            name='last_entered_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9876), django.core.validators.MinValueValidator(1023)]),
        ),
        migrations.AlterField(
            model_name='currentresult',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9876), django.core.validators.MinValueValidator(1023)]),
        ),
    ]
